FROM alpine:latest AS db
ARG PB_VERSION=0.22.11
ARG CADDY_VERSION=2.7.6
RUN apk add --no-cache unzip ca-certificates
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
ADD https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_amd64.tar.gz /tmp/caddy.tar.gz
RUN unzip /tmp/pb.zip -d /pb/ &&\
    mkdir -p /caddy &&\
    tar -xvf /tmp/caddy.tar.gz --directory=/caddy/

FROM node:alpine AS node-base
ENV POCKETBASE_DB=https://db.arch.local
ENV POCKETBASE=0.0.0.0:8090
ENV ORIGIN=https://platform.arch.local

FROM node-base AS builder
WORKDIR /app
COPY package*.json ./
RUN npm i

FROM node-base
COPY ./script/ /bin/script
WORKDIR /pb
COPY --from=db /pb/pocketbase ./
WORKDIR /caddy
COPY --from=db /caddy/caddy ./
WORKDIR /app
COPY --from=builder /app ./
RUN chmod +x /bin/script/script.dev.sh
VOLUME /app
EXPOSE 80
EXPOSE 443
CMD ["/bin/script/script.dev.sh"]
