// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table admins {
  id integer [pk]
  username varchar [unique]
  salt_hashed_password varchar
  login_session_id integer [ref: - login_session.id]
}

Table users {
  id integer [pk]
  first_name varchar
  last_name varchar
  age integer
  email varchar
  username varchar
  salt_hashed_password varchar
  isActive boolean
  last_login_date timestamp
  created_at timestamp
  created_by integer [ref: - admins.id] 
  photo_id integer [ref: - photo.id]
  address_id integer [ref: - address.id]
  login_session_id integer [ref: - login_session.id]
  role_given_date timestamp
}

Table user_role {
  id integer [pk]
  user_id integer [ref: > users.id]
  role_id integer [ref: > role.id]
  created_by integer [ref: - admins.id]
  created_at timestamp
}

Table login_session {
  id integer [pk]
  session_token varchar [unique]
  created_at timestamp
  expires_at timestamp
}

Table role {
  id integer [pk]
  role enum
  description varchar
}

Table activity {
  id integer [pk]
  title varchar
  description varchar
  created_by integer [ref: - admins.id]
  created_at timestamp
  start_date timestamp
  end_date timestamp
  status enum // ['archived', 'postponed', 'disabled', 'active']
  wage_id integer [ref: - wage.id]
  photo_id integer [ref: - photo.id]
  city_id integer [ref: - city.id]
}

Table activity_volunteers {
  user_id integer [ref: > users.id]
  activity_id integer [ref: > activity.id]
  created_by integer [ref: - admins.id]
  created_at timestamp
}

Table activity_responsibles {
  user_id integer [ref: > users.id]
  activity_id integer [ref: > activity.id]
  responsible_type integer [ref: - responsible_type.id]
  repsonsbility_date timestamp
  created_by integer [ref: - admins.id]
  created_at timestamp
}


Table responsible_type {
  id integer [pk]
  respnosible_type enum
}

Table activity_city{
  activity_id integer [ref: > activity.id]
  cityId integer [ref: > city.id]
}

Table wage {
  id integer [pk]  
  working_hour_rate float
  commuting_hour_rate float
  currency_id integer [ref: - currency.id]
}

Table commute {
  id integer [pk]
  user_id integer [ref: > users.id]
  activity_id integer [ref: > activity.id]
  hours float
  is_paid boolean
  commute_date timestamp
  created_date timestamp
  paymnet_date timestamp
}

Table effort {
  id integer [pk]
  user_id integer [ref: > users.id]
  activity_id integer [ref: > activity.id]
  hours float
  is_paid boolean
  effort_date timestamp
  created_date timestamp
  paymnet_date timestamp
}

Table spending {
  user_id integer [ref: > users.id, pk]
  receiptId integer [ref: - receipt.id, pk]
  activity_id integer [ref: > activity.id, pk]
  currency_id integer [ref: > currency.id]
  amount float
  comment varchar
  is_reimbursed boolean
  last_update timestamp
  date timestamp
}

Table receipt {
  id integer [pk]
  photoId integer [ ref: - photo.id]
  receiptType integer [ ref: - receipt_type.id]
  description varchar
}

Table receipt_type {
  id integer [pk]
  type enum
  name varchar
}

Table photo {
  id integer [pk]
  photo blob
  photoType enum
  last_update timestamp
}

Table currency {
  id integer [pk]
  currency_name varchar
  currency_country integer [ref: - country.id]
}

Table address {
  id integer [pk]
  city_id integer [ref: > city.id]
  district varchar
  street varchar
  neighborhood varchar
  building_no varchar
  door_no varchar
}

Table city {
  id integer [pk]
  city_name varchar
  country_id integer [ref: > country.id]
}

Table country {
  id integer [pk]
  country_name varchar
}
